// Code generated by Microsoft (R) AutoRest Code Generator 0.11.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TypeScriptAngularWebApiAppHalSwagger.Proxies.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This represents the collection entity of
    /// {TypeScriptAngularWebApiAppHalSwagger.Models.SalutationModel}.
    /// </summary>
    public partial class SalutationCollectionModel
    {
        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResourceList")]
        public IList<SalutationModel> ResourceList { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_links")]
        public IList<Link> LowLinelinks { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "_embedded")]
        public IList<EmbeddedResource> LowLineembedded { get; set; }

    }
}
